### ISSUE TITLE
Building editcp under macOS/darwin

### ISSUE THREAD

**Issue by cxbrooks** [DaleFarnsworth-DMR/editcp#11]
I have editcp able to download from the MD-UV390 under macOS/darwin.

I'm creating an issue so that my pull request can refer to the issue.

The key thing is that under macOS, to run `qtdeploy build desktop` and to not try to use docker, see [Deploying Linux to macOS](https://github.com/therecipe/qt/wiki/Deploying-Linux-to-macOS):

> This option is strongly recommended against and you should deploy your application from a real macOS device instead.

The other thing I had to do was to copy three files:

```
   cp ../debug/debug_linux.go ../debug/debug_darwin.go
   cp ../dfu/dfu_linux.go ../dfu/dfu_darwin.go
   cp ../stdfu/stdfu_linux.go ../stdfu/stdfu_darwin.go
```

Below are the instructions I followed:

1. Install go and Qt via Homebrew
    1. Install Xcode: `xcode-select --install` or https://itunes.apple.com/us/app/xcode/id497799835
    2. Install [HomeBrew](https://brew.sh/) and run: `export QT_HOMEBREW=true`
    3. Install Qt: `brew install qt`
    4. Install Go: https://golang.org/doc/install?download=go1.13.4.darwin-amd64.pkg
    5. Clone the repo: `go get -v -tags=no_env github.com/therecipe/qt/cmd/...`
    6. Run: `export GO111MODULE=off` (_I'm unsure, but I think this is necessary.  I made this edit after the initial issue creation_)
    7. Run the setup: `$(go env GOPATH)/bin/qtsetup`
2. Get the source code:
```
        go get github.com/dalefarnsworth-dmr/editcp/...
        go get github.com/google/gousb
        go get github.com/tealeg/xlsx
```
3. Build
```
        cd ~/go/src/github.com/dalefarnsworth-dmr/editcp
        qtdeploy build desktop
```
`qtdeploy build desktop `fails with
```
        ../debug/debug.go:47:3: undefined: display
        ../debug/debug.go:98:2: undefined: display
        ../debug/debug.go:102:2: undefined: display
        ../debug/debug.go:106:2: undefined: display
```
4.  Create Darwin-specific files:
```
        cp ../debug/debug_linux.go ../debug/debug_darwin.go
        cp ../dfu/dfu_linux.go ../dfu/dfu_darwin.go
        cp ../stdfu/stdfu_linux.go ../stdfu/stdfu_darwin.go
```
5. Then rerun `qtdeploy build desktop`

The application will be created in `./deploy/darwin/editcp.app` 

To run the app and see stdout/stderr or get a stack trace, run:
`deploy/darwin/editcp.app/Contents/MacOS/editcp`

I'll supply a pull request with these changes sometime over the next couple of days.

**Comment by cxbrooks** [comment]
Thanks for the prompt turnaround on my pull requests!
I was able to build under macOS/darwin.

For the record, I had to add the following to my `~/.bashrc`:
```
export PATH=/usr/local/go/bin:${PATH}
export QT_HOMEBREW=true
export GO111MODULE=off
```
Also, I had a warning when running:
```
bash-3.2$  go get github.com/dalefarnsworth-dmr/editcp/...
# github.com/dalefarnsworth-dmr/ui
dalefarnsworth-dmr/ui/ui.go:153:17: undefined: NewDelayedCallStruct
bash-3.2$
``` 
I'm going to go ahead and close this one.

**Comment by DaleFarnsworth** [comment]
Regarding the undefined NewDelayedCallStruct, go doesn't know to run qtdeploy which will defined NewDelayedCallStruct.  To work around this, run go get -d github.com/dalefarnsworth-dmr/editcp/... instead.
