### ISSUE TITLE
macOS: Read codeplug from radio fails with panic: runtime error: index out of range [-1]

### ISSUE THREAD

**Issue by cxbrooks** [DaleFarnsworth-DMR/editcp#13]
Under macOS, when I try Radio -> Read codeplug from radio, I get a panic:
```
bash-3.2$ ./deploy/darwin/editcp.app/Contents/MacOS/editcp 
panic: runtime error: index out of range [-1]

goroutine 1 [running, locked to thread]:
main.typeFrequencyRange.func3(0xffffffffffffffff)
        github.com/dalefarnsworth-dmr/editcp/editcp.go:524 +0x21d
github.com/therecipe/qt/widgets.callbackQComboBox_CurrentIndexChanged(0x5e70ca0, 0xc0ffffffff)
        github.com/therecipe/qt/widgets/widgets-minimal.go:4972 +0x73
github.com/therecipe/qt/widgets._cgoexpwrap_3c96f3470a08_callbackQComboBox_CurrentIndexChanged(0x5e70ca0, 0xc0ffffffff)
        _cgo_gotypes.go:20383 +0x33
```

Line 524 of editcp.go is marked below:
 ```
       vCbA := ui.NewComboboxWidget(opt, vOptsA, func(index int) {
 524--->        rangeA = vOptsA[index]
                enable := containsString(rangeA, vOptsA[1:])
                rangesA, rangesB = typeFreqRanges(cp, typ)
                if len(rangesB) != 0 {
                        enable = enable && containsString(rangeB, rangesB)
                }
                okButton.SetEnabled(enable)
        })
```
I'm a complete newbie to go, but I think I have a solution, which I'll submit as a pull request.

I think what is happening is that the callback `func(index int)` is being called with -1, which I think indicates that a choice has not been made.  My workaround is to check for -1 and set index to 0 if necessary:
```
        vCbA := ui.NewComboboxWidget(opt, vOptsA, func(index int) {
	        if index == -1 {
                   index = 0
                }
                rangeA = vOptsA[index]
		enable := containsString(rangeA, vOptsA[1:])
                rangesA, rangesB = typeFreqRanges(cp, typ)
                if len(rangesB) != 0 {
			enable = enable && containsString(rangeB, rangesB)
                }
	        okButton.SetEnabled(enable)
        })
```

There was another issue with the lifetime of vOptsB, which I'll describe in a second comment.

**Comment by cxbrooks** [comment]
If I check for -1 in the two places where NewComboboxWidget is created in typeFrequencyRange(), and then do Radio -> Read codeplug from radio and select a single band radio, then try to read a code plug for a dual band radio, I get a panic.

1. Add the check for index == 1 to two places (see above)
2. Build and run 
3. Select Radio -> Read codeplug from radio
4. Select a radio that has only one band, such as the MD-390
5. Click OK.
6. The read hung, probably because my radio is a MD-UV390, so I hit Control-C
7. Run again
8. Select Radio -> Read codeplug from radio
9. Select a dual band radio, such as the MD-UV390
10. In the B range, select a range, such as 400-480 Mhz
11. editcp will exit:
```
bash-3.2$ ./deploy/darwin/editcp.app/Contents/MacOS/editcp 
panic: runtime error: index out of range [3] with length 1

goroutine 1 [running, locked to thread]:
main.typeFrequencyRange.func4(0x3)
        github.com/cxbrooks/editcp/editcp.go:546 +0x23b
github.com/therecipe/qt/widgets.callbackQComboBox_CurrentIndexChanged(0x61bde80, 0x3)
	github.com/therecipe/qt/widgets/widgets-minimal.go:4972 +0x73
github.com/therecipe/qt/widgets._cgoexpwrap_3c96f3470a08_callbackQComboBox_CurrentIndexChanged(0x61bde80, 0x3)
	_cgo_gotypes.go:20383 +0x33
```

I'm not familiar with go, but I think the problem is with the scoping of `vOptsB` in `typeFrequencyRange()`.  If I declare it in a similar fashion to how `vOptsB` is declared and assign to `vOptsB` using `=` instead of `:=`, then the problem goes away.

**Comment by DaleFarnsworth** [comment]
I have a local fix for this that I need to push.

**Comment by cxbrooks** [comment]
Excellent,  please feel free to decline my pull request.

**Comment by cxbrooks** [comment]
I can no longer replicate this issue, so I feel it is fixed.  Closing...
