### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by iddq** [DaleFarnsworth-DMR/editcp#15]
> $ cd editcp
> $ make
> make: *** No rule to make target '../ui/*.go', needed by 'deploy/linux/editcp'.  Stop.

**Comment by DaleFarnsworth** [comment]
You need to get the entire source as described in the README.
go get -d github.com/dalefarnsworth-dmr/editcp/...

**Comment by iddq** [comment]
> $ go get github.com/dalefarnsworth-dmr/editcp/...
>         # github.com/dalefarnsworth-dmr/codeplug
> go/src/github.com/dalefarnsworth-dmr/codeplug/codeplug.go:2145:23: sheet.Rows undefined (type *xlsx.Sheet has no field or method Rows)
> go/src/github.com/dalefarnsworth-dmr/codeplug/codeplug.go:2150:32: sheet.Rows undefined (type *xlsx.Sheet has no field or method Rows)
> # github.com/therecipe/qt/core
> core.cpp:10:3: error: #error ------------------------------------------------------------------
>   #error ------------------------------------------------------------------
>    ^~~~~
> core.cpp:11:3: error: #error please run: '$(go env GOPATH)/bin/qtsetup'
>   #error please run: '$(go env GOPATH)/bin/qtsetup'
>    ^~~~~
> core.cpp:12:3: error: #error more info here: https:
>   #error more info here: https://github.com/therecipe/qt/wiki/Installation
>    ^~~~~
> core.cpp:13:3: error: #error ------------------------------------------------------------------
>   #error ------------------------------------------------------------------
>    ^~~~~
> core.cpp:15:10: fatal error: QAbstractAnimation: No such file or directory
>  #include <QAbstractAnimation>
>           ^~~~~~~~~~~~~~~~~~~~
> compilation terminated.

**Comment by DaleFarnsworth** [comment]
You need to do: go get -d github.com/dalefarnsworth-dmr/editcp/...
Note the "-d".  You may still run into some build issues.
